### ISSUE TITLE
Property for `flex: 1;`

### ISSUE THREAD

**Issue by max** [basscss/flex-object#1]
I'm trying to achieve the following layout:

![image](https://cloud.githubusercontent.com/assets/111631/8840310/4e2f2a02-3094-11e5-90e3-1ab29c5b00e2.png)

Two strings of text side by side, one of which can grow and shrink, and gets truncated if it doesn't fix.

Prior to Chrome 44 this worked:

```
<div class="container">
  <div class="flex">
    <div class="flex-auto">
      <div class="truncate">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid nihil saepe cum iure, repellendus iste illum amet sapiente eos iusto id minima nulla ullam numquam totam fuga ea ipsa.
      </div>
    </div>
    
    <div class="flex-none"><span class="time">2 minutes ago</span></div>
  </div>
</div>
```

Chrome 44 will not truncate the primary text and exceed the overall allowed width by `.container`.

![image](https://cloud.githubusercontent.com/assets/111631/8840366/02e9dbc2-3095-11e5-88f9-a7938c4b239e.png)

As a workaround I added an additional property that produces the desired result:

```
.flex-1 {
  flex: 1;
}
```

Here is a Codepen with both a working and broken example in Chrome 44 (renders fine pre Chrome 44 an Safari in both cases):

http://codepen.io/max/pen/EjerKd

Am I doing something wrong or is a new flex class warranted for this scenario?

**Comment by max** [comment]
Here are some examples from Polymer's layout attributes that use a similar approach: https://github.com/Polymer/polymer/blob/0.5.x/layout.html#L88-L158

**Comment by jxnblk** [comment]
Taking a look into this now. After skimming through https://code.google.com/p/chromium/issues/detail?id=506893 I think setting min-width and min-height 0 to `.flex-auto` might be a better fix. I've forked the Codepen here http://codepen.io/jxnblk/pen/qdJrEX?editors=110 and tested in latest Safari and Firefox.

Using `.flex-1` in your Codepen doesn't seem to work in Firefox, but please let me know if I'm missing something.

**Comment by max** [comment]
@jxnblk Thanks for looking into this. Your fix makes sense to me and fixes my issue. :fireworks:

Out of curiosity, why are you declaring the `flex` property for `.flex-auto` twice? Once as `auto` and once as `1 1 auto`?

**Comment by jxnblk** [comment]
Oh! that was a mistake. Should still work without the second rule.
